version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    hostname: pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  dbdata:
  pgadmin_data: